repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: check-yaml
  - id: check-json
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: requirements-txt-fixer
  - id: check-added-large-files
    args:
      - --maxkb=5000
- repo: https://github.com/ambv/black
  rev: 20.8b0
  hooks:
  - id: black
    language_version: python3
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.8.3
  hooks:
  - id: flake8
- repo: https://github.com/commitizen-tools/commitizen
  rev: v2.4.2
  hooks:
  - id: commitizen
    stages:
      - commit-msg
- repo: https://github.com/timothycrosley/isort
  rev: 5.6.4
  hooks:
    - id: isort
